-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations

CREATE TABLE IF NOT EXISTS "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 2 CACHE 1),
	"name" varchar(15),
	"email" varchar(30) NOT NULL,
	"password" varchar(65) NOT NULL
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "person" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "person_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 4 CACHE 1),
	"name" varchar,
	"city" varchar
);

