CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 2 CACHE 1),
	"name" varchar(15),
	"email" varchar(30) NOT NULL,
	"password" varchar(65) NOT NULL,
	"city" varchar(20)
);
--> statement-breakpoint
CREATE TABLE "address" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 2 CACHE 1),
	"street" varchar(20),
	"city" varchar(20),
	"state" varchar(20),
	"zip" varchar(10)
);
