ALTER TABLE "users" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "id" SET START WITH 2;--> statement-breakpoint
ALTER TABLE "name" DROP COLUMN "father_name";